# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 932fee839517f84fa651851198b389e0f4720754d53617bea3b317f2e7f9697d9c95d56138a8abc1f3bb7d915e4357559d336d883508cc3ea2dec36a1cf7c573

test:
  secret_key_base: d776aa0ac97a9806a0146c16bfff530903a8230d93e4f8a90640de95fd11ac9a07ac4f2fff269169f76f26e0a925fc601a704e6d9d9c51d784ab838b97140481

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
